### PR TITLE
[# 112385907] As a Manager, so that I can track Epic progress, comment on the epic with stats at the start of each iteration 

### PR DESCRIPTION
**Pull request by kquet**
[Tracker #112385907](https://www.pivotaltracker.com/story/show/112385907)

### CODE REVIEW

**Comment by kquet** [comment]
screen shot 2016-01-26 at 5 54 15 pm

**Comment by suwyn** [comment]
kewl.   Suggested label updates:

```
type  count
remaining chores 1
remaining features 2
remaining bugs 1
unstarted points  0
unestimated stories 0
points accepted in last iteration 2
```

**Comment by kenberland** [comment]
@kquet what triggers this to run?

**Comment by kquet** [comment]
@kenberland, currently my keyboard. The story regarding the triggering is found [here](https://www.pivotaltracker.com/story/show/112481015).

**Pull request merged**
